### ISSUE TITLE
the doubt of the 'rpmsg_rpc_client_send() 'function

### ISSUE THREAD

**Issue by huxiangrui** [OpenAMP/open-amp#327]
it's in the linux_rpc_demo.c.
![image](https://user-images.githubusercontent.com/94424839/144999436-5fd3b765-7f9c-420b-9ea1-fb81b44739b7.png)
![image](https://user-images.githubusercontent.com/94424839/144999593-04982683-e3f2-4a11-a5d5-e85e92f818bb.png)
As my understanding, those two memcpy funtion is to fill the tmpbuff in the RPMsg protocol,but the code will not run as my expected.And the tmpbuff will have the same sectors called "TERM_ID".

**Comment by huxiangrui** [comment]
As my understanding, the tmpbuff should be filled in the RPMsg protocol.
![image](https://user-images.githubusercontent.com/94424839/145004772-f8768302-990c-4205-8717-7901ec2e9277.png)

**Comment by arnopo** [comment]
Do you detect an issue or is a question about how to use the rpc service? In the second case please use Q&A discussions thread instead of issue.

That said, please, could you detail what do you mean by "And the tmpbuff will have the same sectors called "TERM_ID"? 
Do you try to run the demo on your Linux PC?

The linux_rpc_demo.c  uses the rpc (remote procedure call) service over the rpmsg protocol.
The tmpbuff is a concatenation of a function ID (OPEN_ID, CLOSE_ID,...) and its associated function parameters. The rpmsg_send will copies the tmpbuff in the payload of the rpmsg and fills the rpmsg header to address the message to the remote endpoint.

**Comment by huxiangrui** [comment]
thanks,i got it.

**Comment by arnopo** [comment]
Could we close the issue in this case ?
